
    <div class="container">
    
    
    
    
    <div class="row col-xs-12 col-sm-12 col-md-12 col-lg-12"  align="center">
    <div class="col-3"></div><div class="col-6">
    <div class="input-group mb-3">
    <input type="text" class="form-control" placeholder="Ramo de atividade" aria-label="Recipient's username" aria-describedby="basic-addon2">
    <div class="input-group-append">
    <button class="btn btn-outline-secondary" type="button">Pesquisar</button>
    </div>
    </div>
    </div>
    </div>
    <div class="row col-xs-12 col-sm-12 col-md-12 col-lg-12"  align="center">
    <div class="col-3"></div><div class="col-6">
    <div class="input-group">
    <div class="input-group-prepend">
    <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Estado</button>
    <div class="dropdown-menu">
    <a class="dropdown-item" href="#">Cidade</a>
    </div>
    </div>
    <input type="text" class="form-control" aria-label="Text input with dropdown button">
    </div>
    </div>
    </div>
    </div>
    
    </div>
    
    
    
    
    
    
    <br>
    
    
    <br>
    </hr>
    <hr>
    <div class="container">
    
    <h3>Últimos Cadastros</h3>
<?= print_r($this->view->ultimos_anuncios); ?>


    <div class="row">
    <div class="col">
    <div class="card" style="width: 18rem;">
    <img class="card-img-top" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22286%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20286%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_174ff3f35ca%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A14pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_174ff3f35ca%22%3E%3Crect%20width%3D%22286%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22107.1953125%22%20y%3D%2296.3%22%3E286x180%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" alt="Card image cap">
    <div class="card-body">
    <h5 class="card-title">Zé da Batata </h5>
    <p class="card-text">Trabalho com pinturas em geral de casa e prédios</p>
    <a href="#" class="btn btn-primary">Visitar Perfil</a>
    </div>
    </div>
    </div>
    <div class="col">
    <div class="card" style="width: 18rem;">
    <img class="card-img-top" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22286%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20286%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_174ff3f35ca%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A14pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_174ff3f35ca%22%3E%3Crect%20width%3D%22286%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22107.1953125%22%20y%3D%2296.3%22%3E286x180%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" alt="Card image cap">
    <div class="card-body">
    <h5 class="card-title">João RalaMuito</h5>
    <p class="card-text">Trabalho com construção e reforma de casas</p>
    <a href="#" class="btn btn-primary">Visitar Perfil</a>
    </div>
    </div>
    </div>
    <div class="col">
    <div class="card" style="width: 18rem;">
    <img class="card-img-top" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22286%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20286%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_174ff3f35ca%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A14pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_174ff3f35ca%22%3E%3Crect%20width%3D%22286%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22107.1953125%22%20y%3D%2296.3%22%3E286x180%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" alt="Card image cap">
    <div class="card-body">
    <h5 class="card-title">Dona Sidineia</h5>
    <p class="card-text">Corte & Costura em Geral de roupas</p>
    <a href="#" class="btn btn-primary">Visitar Perfil</a>
    </div>
    </div>
    </div>
    </div>
    </div>
    
    
    
  
    
    </div>
    