
<form method="POST" action = "/editar_perfil">

    <div class="form-group">
    <label for="nome_publico">Nome Público</label>
    <input type="text" class="form-control"  required="true" id="nome_publico" name="nome_publico" 
            value="<?=$this->view->perfil['nome_publico'] ?>">
    </div>


    <div class="form-group">
    <label for="descricao">Telefone</label>
    <input type="text" class="form-control"  required="true" id="descricao" name="descricao" 
value="<?=$this->view->perfil['telefone'] ?>">
    </div>


    <div class="form-group">
    <label for="fotos">Endereço Comercial</label>
    <input type="text" class="form-control" id="fotos" name="fotos" value="<?=$this->view->perfil['endereco_comercial'] ?>">
    </div>
    <div class="form-group">
    <label for="fotos">Sobre</label>
    <input type="text" class="form-control" id="fotos" name="fotos" value="<?=$this->view->perfil['sobre'] ?>">
    </div>

<div class="form-group">
    <label for="formas_pagamento">Formas de Pagamento</label>
    <select multiple class="form-control" required="true" name ="formas_pagamento[]" id="formas_pagamento">
      <option>Dinheiro</option>
      <option>Cartão de Débito</option>
      <option>Cartão de Crédito</option>
      <option>Cheque</option>
      <option>Outros</option>
</select>
</div>

<div class="form-group">
    <label for="cidade_atuacao">Cidade de atuação</label>
    <select class="form-control" required="true" name="cidade_atuacao_id" id="cidade_atuacao">
        <?php foreach ($this->view->cidades as $id => $valor) {  ?>
          
      <option value=<?= $valor['id'] ?>><?= $valor['nome'] ?></option>
      <?php   }?>
        </select>
    </div>


        <button type="submit" class="btn btn-secondary" value="submit">Alterar Perfil</button>



</div>