


<div class="form-group">
<?php



foreach ($this->view->anuncios as $key => $value) {


?>
<form>
<input type="text" value = <?= $value['id'] ?>>

<input type="text" value = <?= $value['titulo'] ?>>

<input type="text" value = <?= $value['descricao'] ?>>

<input type="text" value = <?= $value['data_inicio'] ?>>

<input type="text" value = <?= $value['fotos_trabalhos'] ?>>


<button type="submit" class="btn btn-secondary" value="submit">Alt</button>
<button type="submit" class="btn btn-secondary" value="submit">Exc</button>

</form>
<?php } ?>



</div>
