<html>
	<head>
		<meta charset="utf-8" />
		<title>Jobbs - Serviços Autonomos</title>

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

		<link rel="stylesheet" href="/css/style.css" />

	</head>

	<body>
<nav class="site-header sticky-top py-1" style="background-color: rgba(0, 0, 0, .85);    backdrop-filter: saturate(180%) blur(20px);
    backdrop-filter: saturate(180%) blur(20px)">
    <div class="container d-flex flex-column flex-md-row justify-content-between">

        <?php 
    if(!isset($_SESSION)) 
    { 
        session_start(); 
    } 
if(isset($_SESSION['autenticado']) && isset($_SESSION['acesso'])){

  ?>

<div class="texto">Seja bem vindo <strong><?= $_SESSION['nome'] ?> </strong></div>
<a class="py-2 d-none d-md-inline-block" href="/logout" role="button">Sair</a>
  
<a class="py-2 d-none d-md-inline-block" href="/meus_anuncios" role="button">Meus Anúncios</a>
  
<a class="py-2 d-none d-md-inline-block" href="/novo_anuncio" role="button">Anunciar Perfil</a>
  
<a class="py-2 d-none d-md-inline-block" href="/meu_perfil" role="button">Meu Perfil Profissional</a>
  
  <?php }else{ ?>
    <a class="py-2 d-none d-md-inline-block" href="/login" role="button">Entrar</a>
    <a class="py-2 d-none d-md-inline-block" href="/signup" role="button">Divulgar meu trabalho</a>
    
	<?php } ?>
    </div>
    </nav>
    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light>
    <div class="row col-xs-12 col-sm-12 col-md-12 col-lg-12 mb-3 ">
<div class="mx-auto">
	 <a href="./"> <img src="jobbs-logo.png" height="350"></a>

    </div>
	</div>
	
	<form action="/pesquisar" metod="GET">
    <div class="pesquisa container">

    <div class="row col-xs-12 col-sm-12 col-md-12 col-lg-12"  align="center">
    <div class="col-3"></div><div class="col-6">
    <div class="input-group mb-3">
    <input type="search" class="form-control" placeholder="ex: pintura,construção,elétrica" 
            name="chave">

    </div>
    </div>
    </div>
        <div class="row col-xs-12 col-sm-12 col-md-12 col-lg-12"  align="center">
            <div class="col-3"></div><div class="col-6">
                <div class="input-group">

                    <input type="text" class="form-control" placeholder="ex: cabo frio, araruama, rj" name="local">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="submit">Pesquisar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    </div>
    </form>     
    
    
    
    
    
    <br>
    
    
    <br>
    </hr>
    <hr>
		<?= $this->content() ?>

		
		<hr>
    Como Funciona | Sobre Nós | Termos de Uso | Privacidade
	</body>

</html>