<html>
	<head>
		<meta charset="utf-8" />
		<title>Jobbs - Serviços Autonomos</title>

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

		<link rel="stylesheet" href="/css/style.css" />

	</head>

	<body>
	<div class="container">
	<div style="background-color: rgba(153, 204, 255, 0.1)">
<?php 
    if(!isset($_SESSION)) 
    { 
        session_start(); 
    } 
if(isset($_SESSION['autenticado']) && isset($_SESSION['acesso'])){

  ?>

  Seja bem vindo  <?= $_SESSION['nome'] ?> <a class="btn btn-lg btn-outline-secondary" href="/logout" role="button" >Sair</a> 
  
  <a class="btn btn-lg btn-outline-secondary" href="/meus_anuncios" role="button" >Meus Anúncios</a>
  
  <a class="btn btn-lg btn-outline-secondary" href="/novo_anuncio" role="button" >Anunciar Perfil</a>
  
  <a class="btn btn-lg btn-outline-secondary" href="/meu_perfil" role="button" >Meu Perfil Profissional</a>
  
  <?php }else{ ?>
    <a class="btn btn-lg btn-outline-secondary" href="/login" role="button" >Entrar</a> 
    <a class="btn btn-lg btn-outline-secondary" href="/signup" role="button" >Divulgar meu trabalho</a>
    
	<?php } ?>
	</div>
    <div class="container mx-auto">
    <div class="row col-xs-12 col-sm-12 col-md-12 col-lg-12 mb-3 ">
    <div class="mx-auto" style="width: 350px;">
	 <a href="./"> <img src="jobbs-logo.png" height="350"></a>

    </div>
	</div>
	

  
    
    <hr>
		<?= $this->content() ?>

		
		<hr>
    Como Funciona | Sobre Nós | Termos de Uso | Privacidade
	</body>

</html>